##                                                   Task -1

#### Data understanding 
#### Data cleaning 
#### Data manipulation 
#### Data visualization

#### For performing task-1 we are using a dataset called "movies" . There we have record of movies from around 10 years & we will try to find a pattern about which kind(genres) of movies are appreciated by public in those years & increment in demands of movies in past 10 years

In [157]:
# Importing necessary libraries

import pandas as pd 
import numpy as np 
pd.set_option('display.max_columns',1000)
pd.set_option('display.max_rows',4000)

In [158]:
# making a dataframe 

df = pd.read_csv('Movies.csv')

In [159]:
df

                 color                     director_name  \
0                Color                     James Cameron
1                Color                    Gore Verbinski
2                Color                        Sam Mendes
3                Color                 Christopher Nolan
4                Color                    Andrew Stanton
5                Color                         Sam Raimi
6                Color                      Nathan Greno
7                Color                       Joss Whedon
8                Color                       David Yates
9                Color                       Zack Snyder
10               Color                      Bryan Singer
11               Color                      Marc Forster
12               Color                    Gore Verbinski
13               Color                    Gore Verbinski
14               Color                       Zack Snyder
15               Color                    Andrew Adamson
16               Color                       Joss Whedon
17               Color                      Rob Marshall
18               Color                  Barry Sonnenfeld
19               Color                     Peter Jackson
20               Color                         Marc Webb
21               Color                      Ridley Scott
22               Color                     Peter Jackson
23               Color                       Chris Weitz
24               Color                     Peter Jackson
25               Color                     James Cameron
26               Color                     Anthony Russo
27               Color                        Peter Berg
28               Color                   Colin Trevorrow
29               Color                        Sam Mendes
30               Color                         Sam Raimi
31               Color                       Shane Black
32               Color                        Tim Burton
33               Color                      Brett Ratner
34               Color                       Dan Scanlon
35               Color                       Michael Bay
36               Color                       Michael Bay
37               Color                         Sam Raimi
38               Color                         Marc Webb
39               Color                   Joseph Kosinski
40               Color                     John Lasseter
41               Color                   Martin Campbell
42               Color                       Lee Unkrich
43               Color                               McG
44               Color                         James Wan
45               Color                      Marc Forster
46               Color                      Bryan Singer
47               Color                       J.J. Abrams
48               Color                      Bryan Singer
49               Color                      Baz Luhrmann
50               Color                       Mike Newell
51               Color                Guillermo del Toro
52               Color                       Michael Bay
53               Color                  Steven Spielberg
54               Color                      Mark Andrews
55               Color                        Justin Lin
56               Color                    Andrew Stanton
57               Color                      Brett Ratner
58               Color                   Roland Emmerich
59               Color                   Robert Zemeckis
60               Color                    Lana Wachowski
61               Color                       David Yates
62               Color                    Andrew Adamson
63               Color                      Bryan Singer
64               Color                 Christopher Nolan
65               Color                       Pete Docter
66               Color                     Rob Letterman
67               Color                       Jon Favreau
68               Color                   Martin Scorsese
69               Color                  Barry Sonnenfeld
70               Color                         Rob Cohen
71               Color                        David Ayer
72               Color                       Tom Shadyac
73               Color                        Doug Liman
74               Color                    Kevin Reynolds
75               Color                   Stephen Sommers
76               Color                       Pete Docter
77               Color                       Jon Favreau
78               Color                       Jon Favreau
79               Color                    Rupert Sanders
80               Color                  Robert Stromberg
81               Color                       Matt Reeves
82               Color                       Carl Rinsch
83               Color                     Anthony Russo
84               Color                     Mike Mitchell
85               Color                         Brad Bird
86               Color                          Don Hall
87               Color                        Rich Moore
88               Color                   Robert Zemeckis
89               Color                   Roland Emmerich
90               Color                      Dean DeBlois
91               Color                   Jonathan Mostow
92               Color                        James Gunn
93               Color                 Christopher Nolan
94               Color                 Christopher Nolan
95               Color                     Peter Jackson
96               Color                         Rob Cohen
97               Color                     David Fincher
98               Color                    Matthew Vaughn
99               Color                  Francis Lawrence
100              Color                    Jon Turteltaub
101              Color                 Wolfgang Petersen
102              Color                       James Bobin
103              Color                      Chris Miller
104              Color                      Duncan Jones
105              Color                       Alan Taylor
106              Color                     Michael Apted
107    Black and White                       Michael Bay
108              Color                       Michael Bay
109              Color                      Oliver Stone
110              Color                       David Yates
111              Color                       Mike Newell
112              Color                        Peter Berg
113              Color                  Francis Lawrence
114              Color                        Tim Burton
115              Color                         Brad Bird
116              Color                 Christopher Nolan
117              Color                      Eric Darnell
118              Color                        Shawn Levy
119              Color                        Gavin Hood
120              Color                    Lana Wachowski
121              Color                        Chris Buck
122              Color                    Lana Wachowski
123              Color                       Alan Taylor
124              Color                     George Miller
125              Color                        Ron Howard
126              Color                   Kenneth Branagh
127              Color                      Byron Howard
128              Color                      Hoyt Yeatman
129              Color                Jonathan Liebesman
130              Color                        Tim Burton
131              Color             Christopher McQuarrie
132              Color                      Joe Johnston
133              Color                     Steve Hickner
134              Color               Jennifer Yuh Nelson
135              Color                M. Night Shyamalan
136              Color                       J.J. Abrams
137              Color                   Roland Emmerich
138              Color                       Simon Wells
139              Color                      David Bowers
140              Color                        Joe Wright
141              Color                       Rob Minkoff
142              Color                 Wolfgang Petersen
143              Color                      Eric Darnell
144    Black and White                      Lee Tamahori
145              Color                         Paul Feig
146              Color                       Michael Bay
147              Color                  Barry Sonnenfeld
148              Color                   Robert Zemeckis
149              Color                Alessandro Carloni
150              Color                         Brad Bird
151              Color                      Peter Ramsey
152              Color                      Dean Parisot
153              Color                      Edward Zwick
154              Color                      Ridley Scott
155              Color                       J.J. Abrams
156              Color                         Sam Raimi
157              Color                      Dean DeBlois
158              Color                       Alex Proyas
159              Color                         Rob Cohen
160              Color                       Zack Snyder
161              Color                    Richard Donner
162              Color                           Ang Lee
163              Color                        Jon M. Chu
164              Color                      Breck Eisner
165              Color                Hironobu Sakaguchi
166              Color                      Joe Johnston
167              Color                     Michael Apted
168              Color                        Peter Weir
169              Color                       Bill Condon
170              Color                     George Miller
171              Color                   Louis Leterrier
172              Color                  Steven Spielberg
173              Color             Alejandro G. Iñárritu
174              Color                       David Soren
175              Color                    Gore Verbinski
176              Color                      Eric Darnell
177              Color                   Paul Greengrass
178              Color                      Mark Osborne
179              Color                       Peyton Reed
180              Color                  Francis Lawrence
181              Color                       Tim Johnson
182              Color                  Steven Spielberg
183              Color                       Michael Bay
184              Color                      Chris Miller
185              Color                     Phillip Noyce
186              Color                  Darren Aronofsky
187              Color                  Steven Spielberg
188              Color                    Alfonso Cuarón
189              Color                      Baz Luhrmann
190              Color                M. Night Shyamalan
191              Color                     Eric Leighton
192              Color                        Shawn Levy
193              Color                       Tom McGrath
194              Color                    Chris Columbus
195              Color                  Robert Schwentke
196              Color                    Gore Verbinski
197              Color                  Francis Lawrence
198              Color                        Ron Howard
199              Color                   Carlos Saldanha
200              Color                      Bryan Singer
201              Color                        Justin Lin
202              Color                       Guy Ritchie
203              Color                   Louis Leterrier
204              Color                    Paul Verhoeven
205              Color                    John McTiernan
206              Color                       Tony Gilroy
207              Color                   Joel Schumacher
208              Color                        Ron Howard
209              Color                   Roland Emmerich
210              Color                          John Woo
211              Color                 Wolfgang Petersen
212              Color                         Tim Story
213              Color                           Ang Lee
214              Color               Mark Steven Johnson
215              Color                   Paul Greengrass
216              Color                               McG
217              Color                      Ridley Scott
218              Color                       Rob Minkoff
219              Color                    Neill Blomkamp
220              Color                       David Twohy
221              Color                      José Padilha
222              Color                    Lana Wachowski
223              Color                   James L. Brooks
224              Color                     James Mangold
225              Color                   Joseph Kosinski
226              Color                      George Lucas
227              Color                      George Lucas
228              Color                       Pete Docter
229              Color                     James Mangold
230              Color                      George Lucas
231              Color                     Kirk De Micco
232              Color                          John Woo
233              Color             Cedric Nicolas-Troyan
234              Color                Jonathan Liebesman
235              Color                    Alfonso Cuarón
236              Color                   Roger Donaldson
237              Color                        Dave Green
238              Color                        Josh Trank
239              Color                        Shawn Levy
240              Color                       Brad Peyton
241              Color                Roger Spottiswoode
242              Color                   Roland Emmerich
243              Color                 Steven Soderbergh
244              Color                        Doug Liman
245              Color                  Robert Schwentke
246    Black and White                   Martin Scorsese
247              Color                     Rob Letterman
248              Color                     Michel Gondry
249              Color                        Noam Murro
250              Color                      Raja Gosnell
251              Color                         Will Finn
252              Color                  Robert Schwentke
253              Color                        Shawn Levy
254              Color                      Raja Gosnell
255              Color                       Jan de Bont
256              Color                        Gavin Hood
257              Color                       Len Wiseman
258              Color                     Peter Jackson
259              Color                      Frank Coraci
260    Black and White                      Michael Mann
261              Color                          Bo Welch
262              Color                       Alex Proyas
263              Color                      Ridley Scott
264              Color                       Rob Minkoff
265              Color                      Ron Clements
266              Color                      Ridley Scott
267              Color                       Michael Bay
268              Color                     Peter Chelsom
269              Color                      Dominic Sena
270              Color                      Ridley Scott
271              Color                  Steven Spielberg
272              Color                    Chris Columbus
273    Black and White                   Martin Campbell
274              Color                        Tim Burton
275              Color                     James Cameron
276              Color                      Michael Mann
277              Color                      Ridley Scott
278              Color                     James Cameron
279              Color                        Tony Scott
280              Color                        Paul Weitz
281              Color                        Adam McKay
282              Color                     Chuck Russell
283              Color                 Quentin Tarantino
284              Color                    Gary Trousdale
285              Color                       Mark Dindal
286              Color                        Simon West
287              Color                    Jon Turteltaub
288    Black and White                  Stefen Fangmeier
289              Color                       Spike Jonze
290              Color                       Chris Wedge
291              Color  Florian Henckel von Donnersmarck
292              Color                       Peter Hyams
293              Color                      Edward Zwick
294              Color                   Martin Scorsese
295              Color                   Joel Schumacher
296              Color                    Paul Verhoeven
297              Color                        Tom Tykwer
298              Color                       Zack Snyder
299              Color                             Pitof
300              Color                      Brett Ratner
301              Color                      Ron Clements
302              Color                   Brad Silberling
303              Color                    Patrick Hughes
304              Color                      Ericson Core
305              Color                 Lawrence Guterman
306              Color                        Ron Howard
307              Color                     Ron Underwood
308              Color                   Paul Greengrass
309              Color                     Steve Martino
310              Color                       David Mamet
311              Color                   Stephen Sommers
312              Color                   Martin Scorsese
313              Color                       Yimou Zhang
314              Color                       Ash Brannon
315              Color                          Frank Oz
316              Color                      Ridley Scott
317              Color                         Jay Roach
318              Color                        Luc Besson
319              Color              Michael Patrick King
320              Color                     Bibo Bergeron
321              Color                     Steve Martino
322              Color                   Kenneth Branagh
323              Color                     Peter Jackson
324              Color                    Andrew Stanton
325              Color                     Peter Jackson
326              Color                     Peter Jackson
327              Color                     Sergey Bodrov
328              Color                        Simon West
329              Color                     Wally Pfister
330              Color                      Joe Johnston
331              Color                      Rupert Wyatt
332              Color                       Mark Waters
333              Color                        John Moore
334              Color                  John Lee Hancock
335              Color                         Brad Bird
336              Color                      Renny Harlin
337              Color                    Chris Columbus
338              Color                  Barry Sonnenfeld
339              Color                     John Lasseter
340              Color                        Tony Scott
341              Color                      Brett Ratner
342              Color                   Robert Zemeckis
343              Color                         Phil Lord
344              Color                   Carlos Saldanha
345              Color                       Ben Stiller
346              Color                               McG
347              Color                   Martin Scorsese
348              Color                     Tony Bancroft

In [160]:
# checking some records of the dataframe 

df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,1873,Polly Walker,1.0,alien|american civil war|male nipple|mars|prin...,http://www.imdb.com/title/tt0401729/?ref_=fn_t...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000

In [161]:
# checking the column names 

df.columns.tolist()

['color',
 'director_name',
 'num_critic_for_reviews',
 'duration',
 'director_facebook_likes',
 'actor_3_facebook_likes',
 'actor_2_name',
 'actor_1_facebook_likes',
 'gross',
 'genres',
 'actor_1_name',
 'movie_title',
 'num_voted_users',
 'cast_total_facebook_likes',
 'actor_3_name',
 'facenumber_in_poster',
 'plot_keywords',
 'movie_imdb_link',
 'num_user_for_reviews',
 'language',
 'country',
 'content_rating',
 'budget',
 'title_year',
 'actor_2_facebook_likes',
 'imdb_score',
 'aspect_ratio',
 'movie_facebook_likes']

In [162]:
# checking the info 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3853 entries, 0 to 3852
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      3851 non-null   object
 1   director_name              3853 non-null   object
 2   num_critic_for_reviews     3852 non-null   float64
 3   duration                   3852 non-null   float64
 4   director_facebook_likes    3853 non-null   float64
 5   actor_3_facebook_likes     3847 non-null   float64
 6   actor_2_name               3852 non-null   object
 7   actor_1_facebook_likes     3853 non-null   float64
 8   gross                      3853 non-null   float64
 9   genres                     3853 non-null   object
 10  actor_1_name               3853 non-null   object
 11  movie_title                3853 non-null   object
 12  num_voted_users            3853 non-null   int64
 13  cast_total_facebook_likes  3853 non-null   int64
 14  actor_3_name               3847 non-null   object
 15  facenumber_in_poster       3847 non-null   float64
 16  plot_keywords              3823 non-null   object
 17  movie_imdb_link            3853 non-null   object
 18  num_user_for_reviews       3853 non-null   float64
 19  language                   3849 non-null   object
 20  country                    3853 non-null   object
 21  content_rating             3805 non-null   object
 22  budget                     3853 non-null   float64
 23  title_year                 3853 non-null   float64
 24  actor_2_facebook_likes     3852 non-null   float64
 25  imdb_score                 3853 non-null   float64
 26  aspect_ratio               3781 non-null   float64
 27  movie_facebook_likes       3853 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 843.0+ KB

In [163]:
# checking statistical terms of the dataframe 

df.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,3852.000000,3852.000000,3853.000000,3847.000000,3853.000000,3.853000e+03,3.853000e+03,3853.000000,3847.000000,3853.000000,3.853000e+03,3853.000000,3852.000000,3853.000000,3781.000000,3853.000000
mean,163.046989,109.921080,784.507397,747.290096,7575.558526,5.096547e+07,1.024240e+05,11239.480145,1.378217,326.720478,4.524817e+07,2003.061511,1959.018432,6.462886,2.109569,9089.546068
std,123.927258,22.741728,3027.395958,1841.623945,15405.383114,6.932033e+07,1.502942e+05,18922.948757,2.056071,407.920904,2.234208e+08,10.007168,4472.171290,1.053843,0.353236,21277.375223
min,1.000000,34.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1920.000000,0.000000,1.600000,1.180000,0.000000
25%,72.000000,95.000000,10.000000,183.000000,721.000000,6.830957e+06,1.730900e+04,1817.000000,0.000000,102.000000,1.000000e+07,1999.000000,362.000000,5.900000,1.850000,0.000000
50%,134.000000,106.000000,58.000000,427.000000,1000.000000,2.790000e+07,5.052300e+04,3876.000000,1.000000,203.000000,2.400000e+07,2005.000000,664.000000,6.600000,2.350000,206.000000
75%,221.000000,120.000000,222.000000,685.000000,12000.000000,6.550000e+07,1.241850e+05,15972.000000,2.000000,391.000000,5.000000e+07,2010.000000,971.000000,7.200000,2.350000,11000.000000
max,813.000000,330.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.300000,16.000000,349000.000000

In [164]:
# checking the shape of the dataframe 

df.shape

(3853, 28)

In [165]:
# checking no. of records of dataframe 

len(df)

3853

In [166]:
# checking value counts in columns 

df['facenumber_in_poster'].value_counts()

facenumber_in_poster
0.0     1627
1.0      980
2.0      541
3.0      296
4.0      165
5.0       78
6.0       57
7.0       33
8.0       32
9.0       13
10.0       7
15.0       5
11.0       5
12.0       3
31.0       1
14.0       1
19.0       1
13.0       1
43.0       1
Name: count, dtype: int64

In [167]:
# checking the missing values in dataframe 

df.isnull().sum()

color                         2
director_name                 0
num_critic_for_reviews        1
duration                      1
director_facebook_likes       0
actor_3_facebook_likes        6
actor_2_name                  1
actor_1_facebook_likes        0
gross                         0
genres                        0
actor_1_name                  0
movie_title                   0
num_voted_users               0
cast_total_facebook_likes     0
actor_3_name                  6
facenumber_in_poster          6
plot_keywords                30
movie_imdb_link               0
num_user_for_reviews          0
language                      4
country                       0
content_rating               48
budget                        0
title_year                    0
actor_2_facebook_likes        1
imdb_score                    0
aspect_ratio                 72
movie_facebook_likes          0
dtype: int64

In [168]:
# finding null count 

null_count = df.isnull().sum()/len(df)

In [169]:
null_count

color                        0.000519
director_name                0.000000
num_critic_for_reviews       0.000260
duration                     0.000260
director_facebook_likes      0.000000
actor_3_facebook_likes       0.001557
actor_2_name                 0.000260
actor_1_facebook_likes       0.000000
gross                        0.000000
genres                       0.000000
actor_1_name                 0.000000
movie_title                  0.000000
num_voted_users              0.000000
cast_total_facebook_likes    0.000000
actor_3_name                 0.001557
facenumber_in_poster         0.001557
plot_keywords                0.007786
movie_imdb_link              0.000000
num_user_for_reviews         0.000000
language                     0.001038
country                      0.000000
content_rating               0.012458
budget                       0.000000
title_year                   0.000000
actor_2_facebook_likes       0.000260
imdb_score                   0.000000
aspect_ratio                 0.018687
movie_facebook_likes         0.000000
dtype: float64

In [170]:
# checking null percentage of each column 

null_perc = pd.DataFrame({ 'column name' : df.columns , 'null perc' : null_count})

In [171]:
null_perc

                                         column name  null perc
color                                          color   0.000519
director_name                          director_name   0.000000
num_critic_for_reviews        num_critic_for_reviews   0.000260
duration                                    duration   0.000260
director_facebook_likes      director_facebook_likes   0.000000
actor_3_facebook_likes        actor_3_facebook_likes   0.001557
actor_2_name                            actor_2_name   0.000260
actor_1_facebook_likes        actor_1_facebook_likes   0.000000
gross                                          gross   0.000000
genres                                        genres   0.000000
actor_1_name                            actor_1_name   0.000000
movie_title                              movie_title   0.000000
num_voted_users                      num_voted_users   0.000000
cast_total_facebook_likes  cast_total_facebook_likes   0.000000
actor_3_name                            actor_3_name   0.001557
facenumber_in_poster            facenumber_in_poster   0.001557
plot_keywords                          plot_keywords   0.007786
movie_imdb_link                      movie_imdb_link   0.000000
num_user_for_reviews            num_user_for_reviews   0.000000
language                                    language   0.001038
country                                      country   0.000000
content_rating                        content_rating   0.012458
budget                                        budget   0.000000
title_year                                title_year   0.000000
actor_2_facebook_likes        actor_2_facebook_likes   0.000260
imdb_score                                imdb_score   0.000000
aspect_ratio                            aspect_ratio   0.018687
movie_facebook_likes            movie_facebook_likes   0.000000

In [172]:
# cross varifying of records 

df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,1873,Polly Walker,1.0,alien|american civil war|male nipple|mars|prin...,http://www.imdb.com/title/tt0401729/?ref_=fn_t...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000

In [173]:
# checking value counts of the 'color' column 

df.color.value_counts()

color
Color               3721
 Black and White     130
Name: count, dtype: int64

In [174]:
# checking value counts of the 'genres' column 

df.genres.value_counts()

genres
Drama                                                               153
Comedy|Drama|Romance                                                151
Comedy|Drama                                                        147
Comedy                                                              145
Comedy|Romance                                                      136
Drama|Romance                                                       119
Crime|Drama|Thriller                                                 82
Action|Crime|Thriller                                                55
Action|Crime|Drama|Thriller                                          50
Action|Adventure|Sci-Fi                                              46
Comedy|Crime                                                         45
Action|Adventure|Thriller                                            45
Horror                                                               43
Crime|Drama                                                          42
Drama|Thriller                                                       42
Crime|Drama|Mystery|Thriller                                         41
Horror|Thriller                                                      34
Action|Adventure|Sci-Fi|Thriller                                     34
Horror|Mystery|Thriller                                              31
Drama|Mystery|Thriller                                               30
Biography|Drama                                                      30
Adventure|Animation|Comedy|Family|Fantasy                            28
Action|Comedy|Crime                                                  27
Horror|Mystery                                                       25
Action|Adventure|Fantasy                                             25
Biography|Drama|Sport                                                23
Action|Thriller                                                      22
Drama|Music                                                          22
Drama|Sport                                                          22
Adventure|Animation|Comedy|Family                                    21
Action|Comedy|Crime|Thriller                                         21
Documentary                                                          21
Biography|Drama|History                                              20
Comedy|Family                                                        20
Action|Crime|Drama|Mystery|Thriller                                  19
Action|Drama|Thriller                                                18
Adventure|Family|Fantasy                                             17
Drama|History|War                                                    17
Mystery|Thriller                                                     17
Comedy|Crime|Drama                                                   17
Comedy|Family|Fantasy                                                17
Drama|War                                                            16
Drama|Music|Romance                                                  16
Action|Sci-Fi                                                        16
Comedy|Sport                                                         16
Comedy|Fantasy                                                       15
Crime|Thriller                                                       15
Crime|Drama|Romance|Thriller                                         15
Fantasy|Horror                                                       15
Biography|Crime|Drama                                                15
Biography|Drama|Romance                                              15
Crime|Mystery|Thriller                                               14
Action|Horror|Sci-Fi|Thriller                                        14
Comedy|Crime|Thriller                                                14
Adventure|Comedy                                                     14
Comedy|Music                                                         14
Comedy|Drama|Romance|Sport                                           13
Action|Sci-Fi|Thriller                                               13
Action|Comedy                                                        13
Comedy|Fantasy|Romance                                               13
Drama|Sci-Fi|Thriller                                                12
Drama|Mystery|Sci-Fi|Thriller                                        12
Action|Adventure|Fantasy|Sci-Fi                                      12
Action|Adventure|Drama|Thriller                                      12
Horror|Sci-Fi|Thriller                                               12
Drama|Fantasy|Romance                                                12
Action|Adventure|Fantasy|Sci-Fi|Thriller                             12
Adventure|Comedy|Family|Fantasy                                      11
Drama|Horror|Mystery|Thriller                                        11
Comedy|Drama|Family                                                  11
Comedy|Drama|Music                                                   11
Action|Crime|Sci-Fi|Thriller                                         11
Comedy|Drama|Fantasy|Romance                                         11
Comedy|Family|Romance                                                11
Comedy|Crime|Romance                                                 11
Adventure|Animation|Family|Fantasy                                   10
Drama|Mystery|Romance|Thriller                                       10
Biography|Drama|Music                                                10
Action|Adventure|Comedy                                              10
Biography|Drama|History|Romance                                       9
Adventure|Comedy|Sci-Fi                                               9
Action|Mystery|Thriller                                               9
Drama|Horror|Thriller                                                 9
Action|Adventure                                                      9
Drama|Romance|War                                                     8
Adventure|Fantasy                                                     8
Drama|Mystery                                                         8
Action|Drama|War                                                      8
Action|Comedy|Sci-Fi                                                  8
Comedy|Horror                                                         8
Fantasy|Horror|Thriller                                               8
Drama|Horror|Sci-Fi|Thriller                                          8
Drama|Family                                                          8
Adventure|Drama                                                       8
Drama|History                                                         8
Comedy|Fantasy|Horror                                                 8
Drama|History|Thriller                                                8
Action|Adventure|Comedy|Family|Sci-Fi                                 8
Action|Adventure|Crime|Thriller                                       8
Comedy|Drama|Music|Romance                                            7
Drama|Sci-Fi                                                          7
Comedy|Crime|Drama|Thriller                                           7
Sci-Fi|Thriller                                                       7
Documentary|Music                                                     7
Action|Comedy|Crime|Drama|Thriller                                    7
Adventure|Comedy|Drama                                                7
Biography|Drama|Thriller                                              7
Adventure|Sci-Fi|Thriller                                             7
Action|Drama|Sci-Fi|Thriller                                          7
Action|Drama                                                          7
Adventure|Animation|Comedy|Family|Sci-Fi                              7
Horror|Sci-Fi                                                         6
Drama|Musical|Romance                                                 6
Action|Drama|Thriller|War                                             6
Action|Adventure|Comedy|Crime                                         6
Action|Horror|Sci-Fi                                                  6
Fantasy|Horror|Mystery|Thriller                                       6
Action|Horror|Thriller                                                6
Action|Crime|Drama|Romance|Thriller                                   6
Action                                                                6
Adventure|Comedy|Family                                               6
Adventure|Drama|Thriller                                              6
Comedy|Fantasy|Horror|Thriller                                        6
Comedy|Documentary                                                    6
Action|Adventure|Drama|Romance                                        6
Action|Crime|Mystery|Thriller                                         6
Action|Adventure|Drama|History|War                                    6
Action|Comedy|Romance                                                 6
Action|Adventure|Drama|Fantasy                                        6
Action|Mystery|Sci-Fi|Thriller                                        6
Drama|Romance|Sport                                                   6
Drama|Fantasy                                                         6
Crime|Horror|Thriller                                                 5
Comedy|Drama|Sport                                                    5
Comedy|Romance|Sci-Fi                                                 5
Animation|Comedy|Family|Fantasy                                       5
Crime|Drama|Romance                                                   5
Crime|Drama|Horror|Thriller                                           5
Comedy|Family|Fantasy|Romance                                         5
Action|Adventure|Comedy|Thriller                                      5
Horror|Mystery|Sci-Fi|Thriller                                        5
Action|Adventure|Romance                                              5
Comedy|Music|Romance                                                  5
Comedy|Romance|Sport                                                  5
Action|Adventure|Fantasy|Thriller                                     5
Mystery|Sci-Fi|Thriller                                               5
Drama|Romance|Sci-Fi                                                  5
Animation|Comedy|Family                                               5
Action|Adventure|Drama                                                5
Action|Drama|History|War                                              5
Adventure|Family|Fantasy|Mystery                                      5
Action|Fantasy|Horror|Thriller                                        5
Drama|Romance|Thriller                                                5
Comedy|Sci-Fi                                                         5
Adventure|Horror|Thriller                                             5
Comedy|Musical|Romance                                                5
Action|Adventure|Family|Fantasy                                       5
Biography|Drama|History|War                                           5
Biography|Crime|Drama|Thriller                                        5
Drama|Romance|Western                                                 5
Action|Adventure|Animation|Comedy|Family                              5
Action|Adventure|Comedy|Sci-Fi                                        5
Adventure|Drama|Sci-Fi                                                4
Drama|Fantasy|Horror                                                  4
Adventure|Drama|Family                                                4
Action|Crime|Drama                                                    4
Adventure|Animation|Comedy|Family|Fantasy|Sci-Fi                      4
Drama|Horror|Sci-Fi                                                   4
Adventure|Drama|Romance                                               4
Drama|Mystery|Romance                                                 4
Drama|Fantasy|Horror|Thriller                                         4
Action|Comedy|Fantasy|Sci-Fi                                          4
Action|Fantasy|Horror                                                 4
Action|Adventure|Horror|Sci-Fi                                        4
Adventure|Biography|Drama|History|War                                 4
Action|Adventure|Animation|Comedy|Family|Fantasy                      4
Biography|Comedy|Drama                                                4
Drama|History|Thriller|War                                            4
Action|Adventure|Comedy|Family|Fantasy|Sci-Fi                         4
Comedy|Crime|Mystery                                                  4
Comedy|Drama|Family|Romance                                           4
Adventure|Drama|Sci-Fi|Thriller                                       4
Action|Adventure|Romance|Sci-Fi|Thriller                              4
Action|Comedy|Thriller                                                4
Action|Adventure|Western                                              4
Drama|Western                                                         4
Adventure|Comedy|Drama|Romance                                        4
Drama|Family|Sport                                                    4
Adventure|Mystery|Sci-Fi                                              4
Adventure|Drama|Romance|War                                           4
Action|Fantasy|Thriller                                               4
Crime|Drama|Mystery                                                   4
Comedy|Crime|Drama|Romance                                            4
Comedy|Horror|Thriller                                                4
Adventure|Drama|Family|Fantasy                                        4
Drama|Mystery|Sci-Fi                                                  4
Biography|Drama|Music|Musical                                         4
Drama|Fantasy|Romance|Sci-Fi                                          3
Comedy|Drama|Family|Sport                                             3
Comedy|Drama|Family|Fantasy                                           3
Adventure|Drama|Western                                               3
Adventure|Biography|Drama                                             3
Adventure|Family                                                      3
Western                                                               3
Comedy|Musical                                                        3
Adventure|Comedy|Family|Romance                                       3
Action|Drama|Sport                                                    3
Adventure|Family|Fantasy|Musical                                      3
Action|Crime|Drama|Thriller|Western                                   3
Action|Comedy|Sport                                                   3
Comedy|Drama|Musical|Romance                                          3
Comedy|Horror|Sci-Fi                                                  3
Horror|Mystery|Sci-Fi                                                 3
Adventure|Drama|History                                               3
Comedy|Drama|Fantasy                                                  3
Crime|Horror|Mystery|Thriller                                         3
Drama|Horror                                                          3
Comedy|Crime|Drama|Romance|Thriller                                   3
Thriller                                                              3
Adventure|Biography|Drama|Thriller                                    3
Action|Adventure|Animation|Comedy|Family|Sci-Fi                       3
Comedy|Western                                                        3
Action|Adventure|Fantasy|Romance                                      3
Adventure|Animation|Comedy|Family|Sport                               3
Biography|Drama|War                                                   3
Comedy|Crime|Romance|Thriller                                         3
Action|Adventure|Horror|Sci-Fi|Thriller                               3
Adventure|Comedy|Fantasy                                              3
Action|Comedy|Crime|Romance|Thriller                                  3
Adventure|Animation|Comedy|Family|Romance                             3
Action|Crime|Fantasy|Thriller                                         3
Drama|Family|Fantasy|Romance                                          3
Drama|Fantasy|Horror|Mystery|Thriller                                 3
Action|Adventure|History                                              3
Drama|History|Romance|War                                             3
Adventure|Drama|Fantasy                                               3
Adventure|Animation|Comedy|Family|Musical                             3
Action|Comedy|Fantasy                                                 3
Comedy|Family|Sci-Fi                                                  3
Adventure|Drama|Fantasy|Romance                                       3
Biography|Comedy|Crime|Drama                                          3
Action|Adventure|Drama|History|Romance                                3
Action|Animation|Comedy|Family|Sci-Fi                                 3
Comedy|Drama|Sci-Fi                                                   3
Action|Drama|Romance                                                  3
Drama|Fantasy|Thriller                                                3
Action|Adventure|Mystery|Sci-Fi|Thriller                              3
Documentary|Sport                                                     3
Biography|Comedy|Drama|History                                        3
Action|Crime|Romance|Thriller                                         3
Adventure|Comedy|Drama|Family|Fantasy                                 3
Action|Adventure|Comedy|Fantasy                                       3
Comedy|Crime|Family                                                   2
Drama|Music|Musical|Romance                                           2
Adventure|Comedy|Mystery                                              2
Action|Drama|Family|Sport                                             2
Action|Adventure|Crime|Mystery|Thriller                               2
Action|Adventure|Animation|Comedy|Drama|Family|Sci-Fi                 2
Drama|Family|Romance                                                  2
Animation|Family|Fantasy|Musical                                      2
Comedy|Drama|Family|Fantasy|Romance                                   2
Animation|Comedy|Family|Sci-Fi                                        2
Adventure|Drama|Mystery                                               2
Comedy|Drama|Horror|Sci-Fi                                            2
Comedy|Fantasy|Sci-Fi                                                 2
Drama|Family|Musical|Romance                                          2
Action|Adventure|Comedy|Western                                       2
Drama|Mystery|Romance|War                                             2
Biography|Drama|History|Thriller                                      2
Drama|History|Sport                                                   2
Adventure|Animation|Comedy|Family|Fantasy|Music                       2
Drama|Fantasy|Musical|Romance                                         2
Drama|Family|Fantasy                                                  2
Action|Adventure|Drama|Sci-Fi                                         2
Action|Adventure|Horror|Thriller                                      2
Action|Drama|Fantasy                                                  2
Action|Comedy|Crime|Romance                                           2

#### Here we can see that we have very less percentage of null value , so it is ok to drop that records

In [175]:
# dropping the records which have missing values 

df.dropna(axis = 0 , inplace = True)

In [176]:
# cross verifying the dataframe after dropping the records 

df.isnull().sum()

color                        0
director_name                0
num_critic_for_reviews       0
duration                     0
director_facebook_likes      0
actor_3_facebook_likes       0
actor_2_name                 0
actor_1_facebook_likes       0
gross                        0
genres                       0
actor_1_name                 0
movie_title                  0
num_voted_users              0
cast_total_facebook_likes    0
actor_3_name                 0
facenumber_in_poster         0
plot_keywords                0
movie_imdb_link              0
num_user_for_reviews         0
language                     0
country                      0
content_rating               0
budget                       0
title_year                   0
actor_2_facebook_likes       0
imdb_score                   0
aspect_ratio                 0
movie_facebook_likes         0
dtype: int64